import { clip, clipMap } from "../clips";
import type { CharacterAssetManifest } from "../types";

export const dravenAssets: CharacterAssetManifest = {
  id: "draven",
  portrait: "/fighters/draven.webp",
  effects: [],
  audio: [],
  clips: clipMap([
    clip("idle", 6, 8),
    clip("walk", 8, 10),
    clip("walkBack", 8, 8),
    clip("dash", 6, 14),
    clip("jumpStart", 3, 12),
    clip("jump", 4, 8),
    clip("fall", 3, 8),
    clip("crouch", 3, 8),
    clip("block", 3, 10),
    clip("blockLow", 3, 10),
    clip("light", 4, 16),
    clip("medium", 5, 14),
    clip("heavy", 7, 11),
    clip("kickLight", 5, 12),
    clip("kickHeavy", 7, 11),
    clip("aerial", 6, 12),
    clip("throw", 10, 10),
    clip("special1", 8, 12),
    clip("special2", 9, 12),
    clip("special3", 12, 10),
    clip("super", 18, 11),
    clip("hit", 3, 10),
    clip("hitHeavy", 5, 8),
    clip("knockdown", 7, 8),
    clip("wakeup", 6, 8),
    clip("victory", 8, 8),
    clip("finish1", 18, 10),
    clip("finish2", 18, 10),
    clip("intro", 6, 8),
    clip("counter", 6, 12),
    clip("taunt", 6, 6),
  ]),
};
