import { clip, clipMap, bindSheets, fighterSheets, bindAvailableClips } from "../clips";
import { NYX_PALETTES } from "../palettes";
import type { CharacterAssetManifest } from "../types";

export const nyxAssets: CharacterAssetManifest = bindAvailableClips({
  id: "nyx",
  portrait: "/fighters/nyx.webp",
  skin: "default",
  availableClips: [],
  palettes: NYX_PALETTES,
  effects: [],
  audio: [],
  clips: bindSheets(clipMap([
    clip("idle", 8, 10),
    clip("walk", 8, 12),
    clip("walkBack", 8, 10),
    clip("dash", 6, 16),
    clip("jumpStart", 3, 14),
    clip("jump", 6, 10),
    clip("fall", 3, 10),
    clip("crouch", 3, 10),
    clip("block", 3, 12),
    clip("blockLow", 3, 12),
    clip("light", 4, 16),
    clip("medium", 5, 14),
    clip("heavy", 7, 12),
    clip("kickLight", 6, 14),
    clip("kickHeavy", 6, 12),
    clip("aerial", 6, 14),
    clip("throw", 8, 12),
    clip("special1", 8, 14),
    clip("special2", 8, 12),
    clip("special3", 10, 12),
    clip("super", 20, 12),
    clip("hit", 4, 12),
    clip("hitHeavy", 5, 10),
    clip("knockdown", 7, 10),
    clip("wakeup", 5, 10),
    clip("victory", 10, 10),
    clip("finish1", 20, 12),
    clip("finish2", 20, 12),
    clip("intro", 8, 10),
    clip("counter", 6, 14),
    clip("taunt", 8, 8),
  ]), fighterSheets("nyx")),
});
