import { clip, clipMap } from "../clips";
import type { CharacterAssetManifest } from "../types";

export const vesperaAssets: CharacterAssetManifest = {
  id: "vespera",
  portrait: "/fighters/vespera.webp",
  effects: [],
  audio: [],
  clips: clipMap([
    clip("idle", 8, 8),
    clip("walk", 8, 9),
    clip("walkBack", 8, 8),
    clip("dash", 6, 12),
    clip("jumpStart", 3, 10),
    clip("jump", 4, 8),
    clip("fall", 3, 8),
    clip("crouch", 3, 8),
    clip("block", 3, 10),
    clip("blockLow", 3, 10),
    clip("light", 5, 12),
    clip("medium", 6, 11),
    clip("heavy", 8, 10),
    clip("kickLight", 5, 12),
    clip("kickHeavy", 7, 10),
    clip("aerial", 6, 11),
    clip("throw", 8, 10),
    clip("special1", 10, 11),
    clip("special2", 12, 10),
    clip("special3", 10, 11),
    clip("super", 20, 11),
    clip("hit", 4, 10),
    clip("hitHeavy", 5, 8),
    clip("knockdown", 7, 8),
    clip("wakeup", 6, 8),
    clip("victory", 10, 8),
    clip("finish1", 18, 10),
    clip("finish2", 18, 10),
    clip("intro", 8, 8),
    clip("counter", 6, 12),
    clip("taunt", 8, 6),
  ]),
};
