import type { CharacterDef } from "./types";

const gatling = ["medium", "heavy", "kickLight", "kickHeavy", "special1", "special2", "special3", "super"];

export const draven: CharacterDef = {
  id: "draven",
  name: "DRAVEN",
  title: "Punhos de Ferro",
  style: "Boxe sujo — rushdown curto, armadura e command grab",
  color: "#8a7a6a",
  accent: "#d9c4a8",
  portrait: "/fighters/draven.webp",
  stats: {
    speed: 300,
    backSpeed: 210,
    jump: 690,
    maxHealth: 1040,
    defense: 1.14,
    strength: 1.16,
    range: 0.74,
    weight: 1.16,
    dashSpeed: 700,
  },
  ratings: { power: 8, speed: 5, defense: 7, range: 3 },
  lore: "Lutava em fossos industriais com as mãos amarradas em ferro. Draven não recua — ele entra, trava e parte ossos até o sino.",
  introLine: "Chega mais. Eu quebro de graça.",
  winLine: "Fica no chão. O ferro já cobrou.",
  specials: ["special1", "special2", "special3"],
  super: "super",
  finishes: [
    {
      id: "finish1",
      name: "Nocaute Sujo",
      command: "66H",
      description: "Dois passos e um gancho no queixo que apaga a luz.",
    },
    {
      id: "finish2",
      name: "Enterrar os Punhos",
      command: "214H",
      description: "Trava a cintura e martela o corpo contra o chão.",
    },
  ],
  combos: [
    { id: "d_b1", name: "Jab Confirmado", level: "basic", sequence: ["light", "light", "medium"], description: "Dois jabs no cruzado." },
    { id: "d_b2", name: "Fígado", level: "basic", sequence: ["kickLight", "heavy"], description: "Chute baixo abre o haymaker." },
    { id: "d_i1", name: "Passo e Gancho", level: "intermediate", sequence: ["light", "medium", "special1"], description: "Cancela o cruzado no Passo de Ferro." },
    { id: "d_i2", name: "Uppercut Sujo", level: "intermediate", sequence: ["kickLight", "medium", "special2"], description: "Baixo para o gancho antiaéreo." },
    { id: "d_a1", name: "Clinch Fatal", level: "advanced", sequence: ["light", "light", "heavy", "special3"], description: "Pressão até o command grab." },
    { id: "d_air", name: "Gancho Voador", level: "air", sequence: ["aerial", "medium"], description: "Aéreo no cruzado no pushback." },
    { id: "d_m1", name: "Armadura e Rajada", level: "meter", sequence: ["special1", "super"], description: "Dash com armadura no Super." },
    { id: "d_c1", name: "Parry de Ombro", level: "counter", sequence: ["counter", "heavy", "special2"], description: "Contra, haymaker e uppercut." },
    { id: "d_p1", name: "Erro no Clinch", level: "punish", sequence: ["throw", "special1"], description: "Agarrão de punição e investida." },
  ],
  moves: {
    light: {
      id: "light", name: "Jab de Ferro", type: "normal", button: "light",
      damage: 46, range: 58, startup: 3, active: 2, recovery: 7, hitStun: 11, blockStun: 6,
      knockback: 70, priority: 2, meterGain: 7, superGain: 4, cancelInto: gatling, height: "mid",
      hitstop: 2,
    },
    medium: {
      id: "medium", name: "Cruzado", type: "normal", button: "medium",
      damage: 78, range: 68, startup: 6, active: 4, recovery: 11, hitStun: 14, blockStun: 9,
      knockback: 130, priority: 3, meterGain: 10, superGain: 5, cancelInto: ["heavy", "kickHeavy", "special1", "special2", "special3", "super"], height: "mid",
      hitstop: 5,
    },
    heavy: {
      id: "heavy", name: "Haymaker", type: "normal", button: "heavy",
      damage: 128, range: 74, startup: 13, active: 4, recovery: 20, hitStun: 19, blockStun: 11,
      knockback: 260, priority: 4, meterGain: 13, superGain: 7, cancelInto: ["special1", "special3", "super"], height: "mid",
      hitstop: 9,
    },
    kickLight: {
      id: "kickLight", name: "Pisada no Joelho", type: "normal", button: "kickLight",
      damage: 50, range: 56, startup: 5, active: 3, recovery: 9, hitStun: 12, blockStun: 6,
      knockback: 80, priority: 2, meterGain: 7, superGain: 3, cancelInto: ["medium", "heavy", "special2"], height: "low",
      hitstop: 3,
    },
    kickHeavy: {
      id: "kickHeavy", name: "Chute no Fígado", type: "normal", button: "kickHeavy",
      damage: 110, range: 64, startup: 11, active: 4, recovery: 18, hitStun: 17, blockStun: 12,
      knockback: 200, priority: 4, meterGain: 11, superGain: 6, cancelInto: ["special1", "super"], height: "mid",
      hitstop: 7,
    },
    aerial: {
      id: "aerial", name: "Gancho Voador", type: "aerial", button: "light",
      damage: 68, range: 70, startup: 5, active: 6, recovery: 8, hitStun: 12, blockStun: 7,
      knockback: 140, priority: 3, meterGain: 8, superGain: 4, height: "high", airOk: true,
      hitstop: 4,
    },
    special1: {
      id: "special1", name: "Passo de Ferro", type: "special", command: "66L",
      damage: 140, range: 88, startup: 8, active: 7, recovery: 16, hitStun: 15, blockStun: 9,
      knockback: 240, priority: 5, meterGain: 5, superGain: 10, cost: 28, cancelInto: ["special3", "super"],
      height: "mid", advance: 560, invuln: 8, hitstop: 6,
    },
    special2: {
      id: "special2", name: "Gancho Sujo", type: "special", command: "623H",
      damage: 155, range: 72, startup: 6, active: 9, recovery: 22, hitStun: 18, blockStun: 8,
      knockback: 180, priority: 6, meterGain: 6, superGain: 10, cost: 32, cancelInto: ["super"],
      height: "high", antiAir: true, invuln: 5, launcher: true, hitstop: 7,
    },
    special3: {
      id: "special3", name: "Quebra-Costela", type: "special", command: "214H",
      damage: 180, range: 62, startup: 7, active: 4, recovery: 26, hitStun: 0, blockStun: 0,
      knockback: 380, priority: 8, meterGain: 8, superGain: 12, cost: 40, cancelInto: ["super"],
      height: "mid", grab: true, knockdown: true, hitstop: 9,
    },
    super: {
      id: "super", name: "Rajada de Ferro", type: "super", command: "236236H",
      damage: 320, range: 90, startup: 6, active: 20, recovery: 26, hitStun: 28, blockStun: 12,
      knockback: 420, priority: 8, meterGain: 0, superGain: 0, superCost: 100, cost: 0,
      height: "mid", hits: 8, invuln: 9, knockdown: true, hitstop: 11, advance: 160,
    },
    throw: {
      id: "throw", name: "Clinch", type: "throw", button: "throw",
      damage: 165, range: 48, startup: 4, active: 3, recovery: 20, hitStun: 0, blockStun: 0,
      knockback: 340, priority: 9, meterGain: 10, superGain: 8, grab: true, knockdown: true, height: "mid",
      hitstop: 7,
    },
    counter: {
      id: "counter", name: "Parry de Ombro", type: "counter", command: "22L",
      damage: 90, range: 64, startup: 3, active: 9, recovery: 18, hitStun: 16, blockStun: 0,
      knockback: 170, priority: 7, meterGain: 12, superGain: 8, invuln: 11, height: "mid",
      hitstop: 6,
    },
    taunt: {
      id: "taunt", name: "Estala os Dedos", type: "taunt", button: "taunt",
      damage: 0, range: 0, startup: 4, active: 1, recovery: 36, hitStun: 0, blockStun: 0,
      knockback: 0, priority: 0, meterGain: 16, superGain: 12, height: "mid",
    },
  },
};
