import type { CharacterDef } from "./types";

const gatling = ["medium", "heavy", "kickLight", "kickHeavy", "special1", "special2", "special3", "super"];

export const kharon: CharacterDef = {
  id: "kharon",
  name: "KHARON",
  title: "O Carrasco",
  style: "Execução brutal — pressão curta, antiaéreo e confirms pesados",
  color: "#c92b35",
  accent: "#ff8a61",
  portrait: "/fighters/kharon.webp",
  stats: {
    speed: 255,
    backSpeed: 175,
    jump: 720,
    maxHealth: 1100,
    defense: 1.18,
    strength: 1.22,
    range: 0.92,
    weight: 1.2,
    dashSpeed: 620,
  },
  ratings: { power: 9, speed: 4, defense: 8, range: 5 },
  lore: "Antigo verdugo da Fortaleza Final. Cada golpe da foice cobra uma dívida de sangue — e Kharon nunca perdoa o saldo.",
  introLine: "A sentença já foi escrita.",
  winLine: "Mais um nome na lista.",
  specials: ["special1", "special2", "special3"],
  super: "super",
  finishes: [
    {
      id: "finish1",
      name: "Degola Ritual",
      command: "66H",
      description: "Avança duas vezes e enterra a foice no pescoço.",
    },
    {
      id: "finish2",
      name: "Empalar",
      command: "236S",
      description: "Baixo, frente e especial — empala o corpo na foice e ergue o troféu.",
    },
  ],
  combos: [
    { id: "k_b1", name: "Sentença", level: "basic", sequence: ["light", "light", "heavy"], description: "Dois cortes rápidos confirmados no pesado." },
    { id: "k_b2", name: "Marca do Carrasco", level: "basic", sequence: ["light", "medium", "kickHeavy"], description: "Soco médio abre o chute que derruba." },
    { id: "k_i1", name: "Investida Confirmada", level: "intermediate", sequence: ["light", "light", "heavy", "special1"], description: "Cancela o pesado na Investida Carmesim." },
    { id: "k_i2", name: "Corte Ascendente", level: "intermediate", sequence: ["kickLight", "medium", "special2"], description: "Chute leve para Guilhotina antiaérea." },
    { id: "k_a1", name: "Veredito", level: "advanced", sequence: ["light", "light", "medium", "heavy", "super"], description: "Gatling completo até o Super." },
    { id: "k_air", name: "Queda do Machado", level: "air", sequence: ["aerial", "heavy"], description: "Ataque aéreo para pesado no pushback." },
    { id: "k_m1", name: "Ceifar e Avançar", level: "meter", sequence: ["special3", "special1"], description: "Projétil para investida, gasta energia." },
    { id: "k_c1", name: "Punição da Foice", level: "counter", sequence: ["counter", "heavy", "special2"], description: "Após o contra-ataque, pesado e antiaéreo." },
    { id: "k_p1", name: "Erro Fatal", level: "punish", sequence: ["heavy", "special1"], description: "Punish de golpe errado à curta distância." },
  ],
  moves: {
    light: {
      id: "light", name: "Corte Curto", type: "normal", button: "light",
      damage: 52, range: 78, startup: 4, active: 3, recovery: 8, hitStun: 12, blockStun: 7,
      knockback: 110, priority: 2, meterGain: 8, superGain: 4, cancelInto: gatling, height: "mid",
      hitstop: 3,
    },
    medium: {
      id: "medium", name: "Talho do Ombro", type: "normal", button: "medium",
      damage: 74, range: 92, startup: 7, active: 4, recovery: 12, hitStun: 15, blockStun: 10,
      knockback: 150, priority: 3, meterGain: 10, superGain: 5, cancelInto: ["heavy", "kickHeavy", "special1", "special2", "special3", "super"], height: "mid",
      hitstop: 5,
    },
    heavy: {
      id: "heavy", name: "Sentença Pesada", type: "normal", button: "heavy",
      damage: 118, range: 102, startup: 12, active: 5, recovery: 18, hitStun: 18, blockStun: 12,
      knockback: 240, priority: 4, meterGain: 13, superGain: 7, cancelInto: ["special1", "special2", "special3", "super"], height: "mid",
      hitstop: 8,
    },
    kickLight: {
      id: "kickLight", name: "Pisoteio", type: "normal", button: "kickLight",
      damage: 48, range: 70, startup: 5, active: 3, recovery: 10, hitStun: 11, blockStun: 6,
      knockback: 90, priority: 2, meterGain: 7, superGain: 3, cancelInto: ["medium", "heavy", "special1"], height: "low",
      hitstop: 3,
    },
    kickHeavy: {
      id: "kickHeavy", name: "Quebra-Joelho", type: "normal", button: "kickHeavy",
      damage: 122, range: 88, startup: 14, active: 5, recovery: 20, hitStun: 20, blockStun: 13,
      knockback: 280, priority: 4, meterGain: 12, superGain: 6, cancelInto: ["special1", "super"], height: "low", knockdown: true,
      hitstop: 8,
    },
    aerial: {
      id: "aerial", name: "Foice Aérea", type: "aerial", button: "light",
      damage: 72, range: 96, startup: 6, active: 8, recovery: 8, hitStun: 12, blockStun: 8,
      knockback: 160, priority: 3, meterGain: 9, superGain: 4, height: "high", airOk: true,
      hitstop: 4,
    },
    special1: {
      id: "special1", name: "Investida Carmesim", type: "special", command: "66L",
      damage: 148, range: 130, startup: 10, active: 8, recovery: 18, hitStun: 16, blockStun: 10,
      knockback: 320, priority: 5, meterGain: 6, superGain: 10, cost: 30, cancelInto: ["super"],
      height: "mid", advance: 520, hitstop: 5,
    },
    special2: {
      id: "special2", name: "Guilhotina", type: "special", command: "623H",
      damage: 160, range: 94, startup: 7, active: 10, recovery: 22, hitStun: 18, blockStun: 8,
      knockback: 200, priority: 6, meterGain: 6, superGain: 10, cost: 35, cancelInto: ["super"],
      height: "mid", antiAir: true, invuln: 6, launcher: true, hitstop: 6,
    },
    special3: {
      id: "special3", name: "Ceifar Almas", type: "special", command: "22H",
      damage: 90, range: 420, startup: 14, active: 4, recovery: 24, hitStun: 14, blockStun: 9,
      knockback: 180, priority: 3, meterGain: 4, superGain: 8, cost: 35, cancelInto: ["super"],
      height: "mid", projectile: "scythe-wave", hitstop: 4,
    },
    super: {
      id: "super", name: "Veredito Infernal", type: "super", command: "236236H",
      damage: 340, range: 160, startup: 8, active: 16, recovery: 28, hitStun: 30, blockStun: 14,
      knockback: 480, priority: 8, meterGain: 0, superGain: 0, superCost: 100, cost: 0,
      height: "mid", hits: 5, invuln: 10, knockdown: true, hitstop: 12, advance: 200,
    },
    throw: {
      id: "throw", name: "Arrasto da Foice", type: "throw", button: "throw",
      damage: 150, range: 52, startup: 5, active: 3, recovery: 22, hitStun: 0, blockStun: 0,
      knockback: 360, priority: 9, meterGain: 10, superGain: 8, grab: true, knockdown: true, height: "mid",
      hitstop: 7,
    },
    counter: {
      id: "counter", name: "Parry do Carrasco", type: "counter", command: "22L",
      damage: 96, range: 80, startup: 3, active: 10, recovery: 20, hitStun: 18, blockStun: 0,
      knockback: 200, priority: 7, meterGain: 12, superGain: 8, invuln: 12, height: "mid",
      hitstop: 6,
    },
    taunt: {
      id: "taunt", name: "Marca a Sentença", type: "taunt", button: "taunt",
      damage: 0, range: 0, startup: 4, active: 1, recovery: 40, hitStun: 0, blockStun: 0,
      knockback: 0, priority: 0, meterGain: 18, superGain: 12, height: "mid",
    },
  },
};
