import type { CharacterDef } from "./types";

const gatling = ["medium", "heavy", "kickLight", "kickHeavy", "special1", "special2", "special3", "super"];

export const nyx: CharacterDef = {
  id: "nyx",
  name: "NYX",
  title: "A Lâmina do Vazio",
  style: "Assassina móvel — mixups, dash e punições longas",
  color: "#6a4cc4",
  accent: "#d697ff",
  portrait: "/fighters/nyx.webp",
  stats: {
    speed: 385,
    backSpeed: 290,
    jump: 860,
    maxHealth: 880,
    defense: 0.88,
    strength: 0.92,
    range: 1.16,
    weight: 0.82,
    dashSpeed: 820,
  },
  ratings: { power: 5, speed: 9, defense: 4, range: 8 },
  lore: "Nasceu na Catedral Negra quando a lua foi engolida. Nyx corta o espaço entre um passo e o outro — e quem pisca, morre.",
  introLine: "Você já está atrasado.",
  winLine: "O vazio não deixa rastros.",
  specials: ["special1", "special2", "special3"],
  super: "super",
  finishes: [
    {
      id: "finish1",
      name: "Perfuração do Coração",
      command: "66H",
      description: "Dois avanços e pesado — as adagas atravessam o peito.",
    },
    {
      id: "finish2",
      name: "Devorar o Vazio",
      command: "22S",
      description: "Baixo, baixo e especial — o eclipse engole o corpo.",
    },
  ],
  combos: [
    { id: "n_b1", name: "Corte Duplo", level: "basic", sequence: ["light", "light", "medium"], description: "Gatling rápido da assassina." },
    { id: "n_sig", name: "Passo da Lua", level: "intermediate", sequence: ["light", "heavy", "special1"], description: "Leve, frente+pesado e Passo do Eclipse. Exclusivo de Nyx." },
    { id: "n_i2", name: "Crescente", level: "intermediate", sequence: ["kickLight", "kickHeavy", "special2"], description: "Chutes para o deslize da Lua Crescente." },
    { id: "n_a1", name: "Noite Sem Fim", level: "advanced", sequence: ["light", "medium", "kickHeavy", "special2", "super"], description: "Launcher para Eclipse Total." },
    { id: "n_air", name: "Queda Silenciosa", level: "air", sequence: ["aerial", "light", "special1"], description: "Aéreo, leve no chão, dash especial." },
    { id: "n_m1", name: "Agulha e Eclipse", level: "meter", sequence: ["special3", "special1"], description: "Projétil para teleporte." },
    { id: "n_c1", name: "Resposta do Vazio", level: "counter", sequence: ["counter", "medium", "special1"], description: "Contra-ataque para dash." },
    { id: "n_p1", name: "Punição Longa", level: "punish", sequence: ["kickHeavy", "special2"], description: "Chute pesado de longo alcance após erro." },
  ],
  moves: {
    light: {
      id: "light", name: "Picada", type: "normal", button: "light",
      damage: 42, range: 88, startup: 3, active: 2, recovery: 7, hitStun: 11, blockStun: 6,
      knockback: 95, priority: 2, meterGain: 9, superGain: 5, cancelInto: gatling, height: "mid",
      hitstop: 3,
    },
    medium: {
      id: "medium", name: "Corte em Arco", type: "normal", button: "medium",
      damage: 62, range: 104, startup: 6, active: 3, recovery: 10, hitStun: 13, blockStun: 8,
      knockback: 130, priority: 3, meterGain: 10, superGain: 5, cancelInto: ["heavy", "kickHeavy", "special1", "special2", "special3", "super"], height: "mid",
      hitstop: 4,
    },
    heavy: {
      id: "heavy", name: "Lâmina Estendida", type: "normal", button: "heavy",
      damage: 88, range: 118, startup: 9, active: 4, recovery: 14, hitStun: 15, blockStun: 10,
      knockback: 190, priority: 3, meterGain: 12, superGain: 6, cancelInto: ["special1", "special2", "special3", "super"], height: "mid",
      hitstop: 7,
    },
    kickLight: {
      id: "kickLight", name: "Chute Farpado", type: "normal", button: "kickLight",
      damage: 46, range: 96, startup: 4, active: 3, recovery: 8, hitStun: 11, blockStun: 6,
      knockback: 100, priority: 2, meterGain: 8, superGain: 4, cancelInto: ["medium", "heavy", "kickHeavy", "special2"], height: "mid",
      hitstop: 3,
    },
    kickHeavy: {
      id: "kickHeavy", name: "Giro da Meia-Noite", type: "normal", button: "kickHeavy",
      damage: 98, range: 124, startup: 11, active: 5, recovery: 16, hitStun: 16, blockStun: 11,
      knockback: 210, priority: 4, meterGain: 12, superGain: 6, cancelInto: ["special1", "special2", "super"], height: "low",
      hitstop: 7,
    },
    aerial: {
      id: "aerial", name: "Queda da Adaga", type: "aerial", button: "light",
      damage: 58, range: 90, startup: 5, active: 10, recovery: 6, hitStun: 12, blockStun: 8,
      knockback: 140, priority: 3, meterGain: 8, superGain: 4, height: "high", airOk: true,
      hitstop: 4,
    },
    special1: {
      id: "special1", name: "Passo do Eclipse", type: "special", command: "66L",
      damage: 128, range: 170, startup: 6, active: 6, recovery: 14, hitStun: 14, blockStun: 8,
      knockback: 240, priority: 5, meterGain: 5, superGain: 10, cost: 30, cancelInto: ["super"],
      height: "mid", advance: 880, invuln: 4, hitstop: 4,
    },
    special2: {
      id: "special2", name: "Lua Crescente", type: "special", command: "236K",
      damage: 140, range: 150, startup: 9, active: 8, recovery: 16, hitStun: 18, blockStun: 9,
      knockback: 160, priority: 4, meterGain: 5, superGain: 10, cost: 30, cancelInto: ["super"],
      height: "low", launcher: true, advance: 420, hitstop: 5,
    },
    special3: {
      id: "special3", name: "Agulha Sombria", type: "special", command: "22L",
      damage: 78, range: 480, startup: 11, active: 3, recovery: 18, hitStun: 12, blockStun: 8,
      knockback: 140, priority: 3, meterGain: 4, superGain: 8, cost: 25, cancelInto: ["super"],
      height: "mid", projectile: "needle", hitstop: 3,
    },
    super: {
      id: "super", name: "Eclipse Total", type: "super", command: "236236L",
      damage: 300, range: 200, startup: 6, active: 22, recovery: 24, hitStun: 28, blockStun: 12,
      knockback: 420, priority: 8, meterGain: 0, superGain: 0, superCost: 100,
      height: "mid", hits: 8, invuln: 12, knockdown: true, hitstop: 10, advance: 300,
    },
    throw: {
      id: "throw", name: "Lançar à Sombra", type: "throw", button: "throw",
      damage: 120, range: 48, startup: 4, active: 3, recovery: 18, hitStun: 0, blockStun: 0,
      knockback: 400, priority: 9, meterGain: 10, superGain: 8, grab: true, knockdown: true, height: "mid",
      hitstop: 6,
    },
    counter: {
      id: "counter", name: "Desvio Lunar", type: "counter", command: "4M",
      damage: 80, range: 90, startup: 2, active: 12, recovery: 16, hitStun: 16, blockStun: 0,
      knockback: 180, priority: 7, meterGain: 12, superGain: 8, invuln: 12, height: "mid",
      hitstop: 5,
    },
    taunt: {
      id: "taunt", name: "Eclipse Mudo", type: "taunt", button: "taunt",
      damage: 0, range: 0, startup: 3, active: 1, recovery: 32, hitStun: 0, blockStun: 0,
      knockback: 0, priority: 0, meterGain: 16, superGain: 14, height: "mid",
    },
  },
};
