import type { CharacterDef } from "./types";

const gatling = ["medium", "heavy", "kickLight", "kickHeavy", "special1", "special2", "special3", "super"];

export const vespera: CharacterDef = {
  id: "vespera",
  name: "VESPERA",
  title: "A Viúva Carmesim",
  style: "Zoning — véus, altares e controle de espaço",
  color: "#7a1230",
  accent: "#e35a7a",
  portrait: "/fighters/vespera.webp",
  difficulty: 4,
  stats: {
    speed: 265,
    backSpeed: 205,
    jump: 760,
    maxHealth: 920,
    defense: 0.9,
    strength: 0.98,
    range: 1.38,
    weight: 0.9,
    dashSpeed: 640,
  },
  ratings: { power: 7, speed: 6, defense: 5, range: 9 },
  lore: "Rainha da Catedral Negra. O sangue obedece ao véu — e quem cruza o altar, não cruza de volta.",
  introLine: "Ajoelhe. O rubro já escolheu.",
  winLine: "O altar está saciado.",
  specials: ["special1", "special2", "special3"],
  super: "super",
  finishes: [
    {
      id: "finish1",
      name: "Véu da Viúva",
      command: "66H",
      description: "Dois passos e o véu abre a garganta.",
    },
    {
      id: "finish2",
      name: "Comunhão Rubra",
      command: "236S",
      description: "O altar sobe e bebe o corpo inteiro.",
    },
  ],
  combos: [
    { id: "v_b1", name: "Látigo", level: "basic", sequence: ["light", "medium", "heavy"], description: "Gatling longo do véu." },
    { id: "v_i1", name: "Altar Confirmado", level: "intermediate", sequence: ["light", "heavy", "special2"], description: "Pesado no altar de sangue." },
    { id: "v_i2", name: "Rosa e Véu", level: "intermediate", sequence: ["kickLight", "special3", "special1"], description: "Baixo, rosa, véu." },
    { id: "v_a1", name: "Corte da Rainha", level: "advanced", sequence: ["light", "medium", "special1", "super"], description: "Projétil para Super." },
    { id: "v_air", name: "Queda Hex", level: "air", sequence: ["aerial", "special1"], description: "Aéreo no véu." },
    { id: "v_m1", name: "Zona Fechada", level: "meter", sequence: ["special2", "special3"], description: "Altar e rosa, gasta energia." },
    { id: "v_c1", name: "Espelho", level: "counter", sequence: ["counter", "special1"], description: "Contra no véu." },
    { id: "v_p1", name: "Erro na Aproximação", level: "punish", sequence: ["heavy", "special2"], description: "Punish de dash longo." },
  ],
  moves: {
    light: {
      id: "light", name: "Toque Rubro", type: "normal", button: "light",
      damage: 44, range: 96, startup: 6, active: 3, recovery: 10, hitStun: 11, blockStun: 6,
      knockback: 90, priority: 2, meterGain: 7, superGain: 4, cancelInto: gatling, height: "mid",
      hitstop: 3,
    },
    medium: {
      id: "medium", name: "Látigo de Véu", type: "normal", button: "medium",
      damage: 70, range: 118, startup: 9, active: 5, recovery: 13, hitStun: 14, blockStun: 9,
      knockback: 140, priority: 3, meterGain: 9, superGain: 5, cancelInto: ["heavy", "kickHeavy", "special1", "special2", "special3", "super"], height: "mid",
      hitstop: 5,
    },
    heavy: {
      id: "heavy", name: "Lança Carmesim", type: "normal", button: "heavy",
      damage: 108, range: 142, startup: 14, active: 6, recovery: 20, hitStun: 17, blockStun: 11,
      knockback: 200, priority: 4, meterGain: 12, superGain: 6, cancelInto: ["special1", "special2", "super"], height: "mid",
      hitstop: 7,
    },
    kickLight: {
      id: "kickLight", name: "Poça", type: "normal", button: "kickLight",
      damage: 48, range: 88, startup: 7, active: 4, recovery: 12, hitStun: 12, blockStun: 7,
      knockback: 80, priority: 2, meterGain: 7, superGain: 3, cancelInto: ["medium", "special2", "special3"], height: "low",
      hitstop: 3,
    },
    kickHeavy: {
      id: "kickHeavy", name: "Coroa Invertida", type: "normal", button: "kickHeavy",
      damage: 96, range: 110, startup: 15, active: 5, recovery: 22, hitStun: 16, blockStun: 10,
      knockback: 180, priority: 3, meterGain: 10, superGain: 5, cancelInto: ["special1", "super"], height: "high", overhead: true,
      hitstop: 6,
    },
    aerial: {
      id: "aerial", name: "Hex Cadente", type: "aerial", button: "light",
      damage: 64, range: 100, startup: 7, active: 8, recovery: 10, hitStun: 12, blockStun: 7,
      knockback: 130, priority: 3, meterGain: 8, superGain: 4, height: "high", airOk: true,
      hitstop: 4,
    },
    special1: {
      id: "special1", name: "Véu Rubro", type: "special", command: "236L",
      damage: 86, range: 460, startup: 16, active: 4, recovery: 26, hitStun: 13, blockStun: 8,
      knockback: 160, priority: 3, meterGain: 4, superGain: 8, cost: 28, cancelInto: ["super"],
      height: "mid", projectile: "veil", hitstop: 4,
    },
    special2: {
      id: "special2", name: "Altar de Sangue", type: "special", command: "22H",
      damage: 110, range: 280, startup: 18, active: 6, recovery: 28, hitStun: 16, blockStun: 10,
      knockback: 120, priority: 4, meterGain: 5, superGain: 9, cost: 36, cancelInto: ["super"],
      height: "low", projectile: "altar", hitstop: 5,
    },
    special3: {
      id: "special3", name: "Rosa Negra", type: "special", command: "214K",
      damage: 132, range: 160, startup: 12, active: 8, recovery: 22, hitStun: 18, blockStun: 9,
      knockback: 220, priority: 5, meterGain: 5, superGain: 10, cost: 32, cancelInto: ["super"],
      height: "mid", advance: -80, hitstop: 6,
    },
    super: {
      id: "super", name: "Corte da Rainha", type: "super", command: "236236H",
      damage: 310, range: 420, startup: 10, active: 18, recovery: 30, hitStun: 26, blockStun: 12,
      knockback: 380, priority: 8, meterGain: 0, superGain: 0, superCost: 100, cost: 0,
      height: "mid", hits: 6, invuln: 8, knockdown: true, hitstop: 11, projectile: "veil",
    },
    throw: {
      id: "throw", name: "Laço de Véu", type: "throw", button: "throw",
      damage: 140, range: 50, startup: 5, active: 3, recovery: 22, hitStun: 0, blockStun: 0,
      knockback: 340, priority: 9, meterGain: 10, superGain: 8, grab: true, knockdown: true, height: "mid",
      hitstop: 7,
    },
    counter: {
      id: "counter", name: "Espelho de Sangue", type: "counter", command: "4M",
      damage: 88, range: 86, startup: 3, active: 10, recovery: 18, hitStun: 16, blockStun: 0,
      knockback: 190, priority: 7, meterGain: 12, superGain: 8, invuln: 11, height: "mid",
      hitstop: 6,
    },
    taunt: {
      id: "taunt", name: "Benção Fria", type: "taunt", button: "taunt",
      damage: 0, range: 0, startup: 4, active: 1, recovery: 38, hitStun: 0, blockStun: 0,
      knockback: 0, priority: 0, meterGain: 16, superGain: 12, height: "mid",
    },
  },
};
